spring:
  profiles: demo3-verb

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/ 

words: ran,knew,had,saw,bought

---
  
spring:
  profiles: demo3-noun

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/ 

words: boat,book,vote,seat,backpack,partition,groundhog
