
spring:
  profiles: demo3-verb
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/ 
words: ran,knew,had,saw,bought

---
  
spring:
  profiles: demo3-noun
words: boat,book,vote,seat,backpack,partition,groundhog
   
---
  
spring:
  profiles: demo3-adjective
words: breasonable,leaky,suspicious,ordinary,unlikely
      
---
  
spring:
  profiles: demo3-article
words: a,the

---
  
spring:
  profiles: demo3-subject
words: I,You,He,She,It


