eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/ 

----
spring:
  profiles: demo3-verb
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/ 
words: ran,knew,had,saw,bought
  
