
spring:
  profiles: demo3-verb
words: ran,knew,had,saw,bought
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/ 
---
  
spring:
  profiles: demo3-noun
words: boat,book,vote,seat,backpack,partition,groundhog
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/ 
      
---
  
spring:
  profiles: demo3-adjective
words: breasonable,leaky,suspicious,ordinary,unlikely
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/ 
      
---
  
spring:
  profiles: demo3-article
words: a,the
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/ 
      
---
  
spring:
  profiles: demo3-article
words: a,the
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/ 


